name: Update

on:
  push:
  schedule:
    - cron: 0 8 * * * 

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Update
      run: |
        # 获取源
        rm -f General.m3u && touch General.m3u
        wget https://raw.githubusercontent.com/atsushi444/iptv/refs/heads/main/adult.m3u -O Adult.m3u
        wget https://raw.githubusercontent.com/atsushi444/iptv/refs/heads/main/adult2.m3u -O Adult2.m3u 
        cat Adult.m3u >> General.m3u
        cat Adult2.m3u >> General.m3u
        sed -i '1i #EXTM3U' General.m3u
        sed -i '/^\s*$/d' General.m3u

        
        # 整合源
        rm -f General.m3u && touch General.m3u
        cat General.m3u >> General.m3u
        sed -i '/#EXTM3U/d' General.m3u
        sed -i '1i #EXTM3U' General.m3u
        sed -i '/^\s*$/d' General.m3u

        # 更新时间

        echo "Auto Update IPTV in ${GET_TIME}" > README.md

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${GET_TIME}"
        git branch -D main
        git branch -m main

    - name: Push
      run: git push -f origin main

